name: Game Report
description: Give feedback for a game.
title: "[Rating]: "
labels: ["report"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: steamvr
    attributes:
      label: SteamVR
      description: Did you try using SteamVR? How did it work?
      options:
        - Perfect
        - Requires manual configuration
        - Playable with graphical/controller issues
        - Unplayable because of graphical/controller issues
        - Crashes or won't start
    validations:
      required: false
  - type: dropdown
    id: monado
    attributes:
      label: Monado
      description: Did you try using Monado? How did it work?
      options:
        - Perfect
        - Requires manual configuration
        - Playable with graphical/controller issues
        - Unplayable because of graphical/controller issues
        - Crashes or won't start
    validations:
      required: false
  - type: dropdown
    id: alvr
    attributes:
      label: ALVR
      description: Did you try using ALVR? How did it work?
      options:
        - Perfect
        - Requires manual configuration
        - Playable with graphical/controller issues
        - Unplayable because of graphical/controller issues
        - Crashes or won't start
    validations:
      required: false
  - type: dropdown
    id: wivrn
    attributes:
      label: WiVRn
      description: Did you try using WiVRn? How did it work?
      options:
        - Perfect
        - Requires manual configuration
        - Playable with graphical/controller issues
        - Unplayable because of graphical/controller issues
        - Crashes or won't start
    validations:
      required: false
  - type: dropdown
    id: gpu
    attributes:
      label: GPU vendor
      description: Are you using an Nvidia, Intel or AMD GPU?
      options:
        - Nvidia
        - Intel
        - AMD
    validations:
      required: false
  - type: input
    id: distro
    attributes:
      label: Distribution
  - type: input
    id: device
    attributes:
      label: Headset  
  - type: textarea
    id: text
    attributes:
      label: Description
      description: Please provide your experience with the software.
      placeholder: Tell us what worked and what didn't. If possible verion information such as Distributon, kernel, gpu drivers, proton version... would be awesome!
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date  
 
